# token of the bot that's going to be used
bot_token: sample.bot_token

# User ID of the owner
owner_id: 123456789

# Text channel ID of the guild you want to bind to Minecraft 
chat_channel: 987654321

# Set the prefix of your command
command_executor: "~!"

# ID's of people who has permissions to do MineCordBot commands
whitelist:
  - 193970511615623168
