# config version
CONFIG_VERSION: 0.2.8

# token of the bot that's going to be used
bot_token: sample.bot_token

# User ID of the owner
owner_id: 123456789

# Set the prefix of your command
command_executor: "~!"

# Text channel ID of the guild you want to bind to Minecraft
chat_channel:
  - 9876543212
  - 9382382323

# ID's of people who has permissions to do MineCordBot commands
whitelist:
  - 193970511615623168

# message prefix that will be seen in Discord
message_prefix_discord: Minecraft

# message prefix that will be seen in minecraft. This support conventional Bukkit Formatting. i.e &6, &e, etc.
message_prefix_minecraft: Discord

# toggle different events to be broadcasted on discord
broadcast:
    death_event: true
    join_event: true
    leave_event: true
    hide_user_with_incognito_perm: false
