name: MineCordBot
version: 0.1.7
author: CyRien
description: Discord bot that bridge chat from minecraft to discord

main: eb.cyrien.MineCordBot.Main

commands:
    dme:
        description: Discord /me
        usage: /dme <message>
        permission: MineCordBot.dme
    CFABot:
        description: MineCordBot general commands
        usage: /CFA <command>
permmission:
    minecordbot.dme:
        default: op
    minecordbot.reload:
        default: op