name: MineCordBot
version: 0.2.2
author: CyRien
description: Discord bot that bridge chat from minecraft to discord

main: eb.cyrien.MineCordBot.Main

commands:
    dme:
        description: Discord /me
        usage: /dme <message>
        permission: MineCordBot.dme
    minecordbot:
        description: MineCordBot general commands
        usage: /CFA <command>
    dcmd:
        description: Do discord commands from minecraft
        usage: /dcmd <Discord command> {args...}
permmission:
    minecordbot.dme:
        default: op
    minecordbot.reload:
        default: op
    minecraftbot.dcmd:
        default: op