name: CFABot
version: 0.1.7
author: CyRien
description: Discord bot that bridge chat from minecraft to discord

main: eb.cyrien.CFABot.Main

commands:
    dme:
        description: Discord /me
        usage: /dme <message>
        permission: CFABot.dme
    CFABot:
        description: CFABot general commands
        usage: /CFA <command>
permmission:
    CFABot.dme:
        default: op
    CFABot.reload:
        default: op